### ISSUE TITLE
Convert GFF to isomiRs input

### ISSUE THREAD

**Issue by lpantano** [miRTop/mirtop#20]
It needs to convert from a GFF file:

https://github.com/miRTop/mirtop/blob/dev/data/examples/gff/correct_file.gff

to a file like this:

https://github.com/miRTop/mirtop/blob/dev/data/examples/seqbuster/reads20.mirna

To be compatible with https://github.com/lpantano/isomiRs

This can be implemented inside `gff` folder inside `convert.py` file. And it should be called as `mirtop make -i GFF_FILE --format isomiRs -o OUT_FOLDER`

**Comment by sbb25** [comment]
Hi Lorena, 
I'm trying to push to the repo and don't have permissions. Would you be able to add me to this repo?

**Comment by lpantano** [comment]
Hi can be continue here: https://gitter.im/mirtop/devel. I can help you then. We would like to use the fork  - PR strategy here.
