### ISSUE TITLE
Accept `N` character for UID creation

### ISSUE THREAD

**Issue by lpantano** [miRTop/mirtop#24]
The main code is here `align ` function:

https://github.com/miRTop/mirtop/blob/dev/mirtop/mirna/realign.py#L150

The function should return the first sequence without `N` character. If find one, it should take the corresponding character from the second sequence in the function.

Try this to look at the current output:

https://github.com/miRTop/mirtop/blob/dev/test/test_functions.py#L83

For instance in this case:

```
align("TGANGTAGTAGGTTGTATAGTT", "TGAGGTAGTAGGTTGTATAGTT")
```

It should give:

```
('TGAGGTAGTAGGTTGTATAGTT', 'TGAGGTAGTAGGTTGTATAGTT', 22.0, 0, 22)
```

Feel free to ask any question.

**Comment by sbb25** [comment]
Lorena, 
here's a pseudo -
method align(x,y): 
  if len(x) == len(y): 
     nindex = [find all indices of x where "N"]
     for index in nindex: 
         x = x.replace(x[index], y[index])
  run pairwise for the new_x, y - pairwise2.align.globalms(new_x, y, 1, -1, -1, -0.5)[0]

This way, it only works when x and y are of equal length. What happens when len(x) != len(y) ?
