### ISSUE TITLE
Trailing Slash for samples

### ISSUE THREAD

**Issue by JFsanchezherrero** [miRTop/mirtop#52]
Dear mirtop developers,
I have noticed a bug in the last version of mirtop (0.3.17) when dealing with back slashes.

I run mirtop gff conversion from sRNAbench data. 

`mirtop gff --sps hsa --hairpin ../sRNAtoolboxDB/libs/hairpin.fa --gtf ../hsa.gff3 --format srnabench -vd -o test1 isomiR_sRNAbenchtoolbox/sample_1/`

I noticed that if I leave the backslash for the folder from sRNAbench data ( isomiR_sRNAbenchtoolbox/sample_1/), mirtop gff generates only a mirtop.gff file with no COLDATA information.

**_## mirGFF3. VERSION 0.9_**
**_## source-ontology: miRBasev22 doi:10.25504/fairsharing.hmgte8_**
**_## COLDATA:_** 

But if I removed the backslash, (isomiR_sRNAbenchtoolbox/sample_1) mirtop gff would generate a mirtop.gff and a sample_1.gff file containing information in the COLDATA section

**_## mirGFF3. VERSION 0.9_**
**_## source-ontology: miRBasev22 doi:10.25504/fairsharing.hmgte8_**
**_## COLDATA: sample_1_**

I know it is not a big issue, but I took a while to discover why mirtop stats was failing after mirtop gff step. 

Adding a back slash is a very common practice and some users might experience the same problem. Adding a simple if folder.endswith("/") clause should sort it out.

Thank you very much in advance,

Great code and program!
Greetings from IGTP

**Comment by lpantano** [comment]
Hi!

Thanks so much for debugging this.

I will test this with the devel branch and see whether we still have it, it
is a very annoying bug!

Thanks so much for your help!

Cheers

Lorena Pantano, P.h.D

Research Scientist

Biostatistics Department

Harvard T.H. Chan School of Public Health

https://mirtop.github.io

https://lpantano.github.io


I'll be out of office from Dec-17th to Jan9th

**Comment by lpantano** [comment]
Hi,

this is fixed in the devel version.

Thanks!
